set -e
true
true
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/spades-core /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K21/configs/config.info /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K21/configs/careful_mode.info
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/spades-core /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K33/configs/config.info /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K33/configs/careful_mode.info
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/spades-core /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K55/configs/config.info /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K55/configs/careful_mode.info
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/spades-core /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/configs/config.info /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/configs/careful_mode.info
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/python /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/share/spades/spades_pipeline/scripts/copy_files.py /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/before_rr.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/before_rr.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/assembly_graph_after_simplification.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/assembly_graph_after_simplification.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/final_contigs.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/contigs.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/first_pe_contigs.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/first_pe_contigs.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/strain_graph.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/strain_graph.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/scaffolds.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/scaffolds.fasta /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/scaffolds.paths /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/scaffolds.paths /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/assembly_graph_with_scaffolds.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/assembly_graph_with_scaffolds.gfa /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/assembly_graph.fastg /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/assembly_graph.fastg /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/K77/final_contigs.paths /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/contigs.paths
true
true
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/python /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/contigs.fasta --assembled /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1 --bin_home /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/python /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/scaffolds.fasta --assembled /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1 --bin_home /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin
true
/home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/bin/python /home/viper/.local/share/mamba/envs/VIPERGenomeAssembler/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/scaffolds.fasta --misc_dir /opt/viper/src/Test_samples/testFLU/FLU__FLU_1_TEST_SAMPLE_S0__testFLU/SPAdes_segment1/misc --threshold_for_breaking_scaffolds 3
true
